package br.com.si.CrudApp.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.hateoas.RepresentationModel;

import javax.persistence.*;

@Entity
@Table(name = "brand")
@AllArgsConstructor
@NoArgsConstructor
@ApiModel(value = "Brand Model")

public class BrandModel extends RepresentationModel {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Setter @Getter
    @ApiModelProperty(notes = "The ID, auto generated by database", required = true)
    private long id;

    @Column(name="description", nullable = false, length = 50)
    @Setter @Getter
    @ApiModelProperty(notes = "The name of brand", required = true)
    private String description;


}
