package br.com.si.CrudApp.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.hateoas.RepresentationModel;

import javax.persistence.*;

@Entity
@Table(name = "model")
@AllArgsConstructor
@NoArgsConstructor
@ApiModel(value = "Model V2")
public class ModelModel extends RepresentationModel {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Setter @Getter
    @ApiModelProperty(notes = "The ID, auto generated by database", required = true)
    private long id;

    @Column(name ="description", nullable = false, length = 50)
    @Setter @Getter
    @ApiModelProperty(notes = "Model Name", required = true)
    private String description;

    @Column(name ="engine_power", nullable = false, length = 50)
    @Setter @Getter
    @ApiModelProperty(notes = "The Engine Power", required = true)
    private String engine_power;

    @Column(name ="doors", nullable = false)
    @Setter @Getter
    @ApiModelProperty(notes = "How Many Doors the Model have?", required = true)
    private Integer doors;

    @Column(name ="color", nullable = false, length = 50)
    @Setter @Getter
    @ApiModelProperty(notes = "The Color of The Model", required = true)
    private String color;

    @ManyToOne
    @JoinColumn(name = "brand_id")
    @Getter @Setter
    private BrandModel brand;

}
